### PR TITLE
Verify no dups array list

### PR DESCRIPTION
**Pull request by frozenfrank**
Requesting to merge into the `2024winter` branch to avoid confusion from multiple versions of the test cases this year.

This is a clone of softwareconstruction240/chess#4 which was recently merged. As a result of softwareconstruction240/chess#5, this code in a separate repository is now out of date. Here I present the PR to keep the changes in sync, but the real solution is to put all the relevant code into the same repository to avoid this kind of issue in the future.

### CODE REVIEW

**Comment by leesjensen** [comment]
@frozenfrank - I'm confused by this comment:

> This is a clone of https://github.com/softwareconstruction240/chess/pull/4 which was recently merged. As a result of https://github.com/softwareconstruction240/chess/issues/5, this code in a separate repository is now out of date. Here I present the PR to keep the changes in sync, but the real solution is to put all the relevant code into the same repository to avoid this kind of issue in the future.

There is no code shared by github.com/softwareconstruction240/chess and github.com/softwareconstruction240/softwareconstruction. All the changes you are proposing here are in github.com/softwareconstruction240/softwareconstruction, but you reference github.com/softwareconstruction240/chess in you comment. What does it mean to "put all the relevant code into the same repository" and what was "this kind of issue" that you are referring to?

**Comment by leesjensen** [comment]
It looks like you are trying to sync up the winter2024 branch for `softwareconstruction` to the lastest code through a pull request and then add some more changes to the instruction. You don't need to do this. The branch is only for changes to the starter code, or changes to the rubric, that we don't want to deploy until the semester is over. All the other changes can go directly into main. Can you do a pull request against `main` that simply has your changes starting at `7bce889`. Thanks!

**Comment by frozenfrank** [comment]
@leesjensen 
> It looks like you are trying to sync up the winter2024 branch for `softwareconstruction` to the lastest code through a pull request and then add some more changes to the instruction. You don't need to do this. All the other changes can go directly into main. Can you do a pull request against `main` that simply has your changes starting at `7bce889`. Thanks!

Do I have to create a new PR, or can I update this PR with the correct commits? I did make a mistake, but I could fix it by rebasing my adjustments onto the `winter2024` branch.

**Comment by frozenfrank** [comment]
@leesjensen 

> There is no code shared by github.com/softwareconstruction240/chess and github.com/softwareconstruction240/softwareconstruction. All the changes you are proposing here are in github.com/softwareconstruction240/softwareconstruction, but you reference github.com/softwareconstruction240/chess in you comment. What does it mean to "put all the relevant code into the same repository" and what was "this kind of issue" that you are referring to?

That's not quite true. Not all of the changes proposed here were in the `2024winter` branch. There is one commit of new information. Now that the branch has been updated, this would be more obvious, expect that the PR stops updating when it is closed. As requested, though not necessitated by GitHub, I'll open a new pull request to continue the discussion of the changes.

**Pull request closed without merging**
